### ISSUE TITLE
DaemonSet type for Pomerium 

### ISSUE THREAD

**Issue by ramzcode** [pomerium/pomerium-helm#241]
Hi,

Is there a way to install Pomerium using helm chart as a daemonset ? Please let us know.

**Comment by travisgroth** [comment]
Hi @ramzcode,

No, there isn't an option for that.

Can you elaborate on the use case/reasoning?

**Comment by travisgroth** [comment]
Typically that's done by increasing the replica count and setting pod anti-affinity rules so that replicas avoid running on the same node.  During maintenance, the pods should get evicted correctly; but the anti-affinity will keep unexpected node failures from impacting too many proxies.

The chart also supports pod autoscaling so that you can keep pomerium scaled up based on your utilization rather than node count.

**Comment by ramzcode** [comment]
@travisgroth  Great to know, thanks a lot. Will plan and build the environment accordingly.
